include(CMakeForceCompiler)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER "/home/lighthouse/arm-toolchain/bin/arm-none-eabi-gcc")
set(OBJCOPY "/home/lighthouse/arm-toolchain/bin/arm-none-eabi-objcopy")
add_compile_options(-mcpu=cortex-m3 -mthumb -g)
set(LINKER_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/layout.ld)
set(CMAKE_EXE_LINKER_FLAGS "-T${LINKER_SCRIPT} -nostdlib")
set(CMAKE_FIND_ROOT_PATH "/home/lighthouse/arm-toolchain/lib/gcc/arm-none-eabi/12.3.1")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
